# 10-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-repo
  namespace: demo-eda
spec:
  replicas: 1
  selector:
    matchLabels: { app: mini-repo }
  template:
    metadata:
      labels: { app: mini-repo }
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: app
        image: quay.io/mcaballol/mini-repo:latest
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          httpGet: { path: /healthz, port: http }
          initialDelaySeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: http }
          initialDelaySeconds: 10